name: u_credit_card
description: uCreditCard - Easy to use beautiful Card UI Flutter Package.
version: 1.4.0
homepage: "https://github.com/utpal-barman/u-credit-card-flutter"
repository: "https://github.com/utpal-barman/u-credit-card-flutter"
topics:
  - creditcard
  - credit
  - card
  - ucreditcard
  - debitcard

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ">=0.3.0 <2.0.0"
  very_good_analysis: ">=3.1.0 <7.0.0"

flutter:
  assets:
    - assets/images/

  fonts:
    - family: ocr-a
      fonts:
        - asset: fonts/OCR-A-regular.ttf

screenshots:
  - description: The uCreditCard package logo.
    path: screenshots/uCreditCard.png
